# @Author: 欧鹏程
# @Date:   2018-04-20T21:19:38+08:00
# @Email:  pengchengou@gmail.com
# @Filename: .travis.yml
# @Last modified by:   欧鹏程
# @Last modified time: 2018-04-20T21:32:44+08:00
# @License: MIT
language: node_js
node_js: '9'
dist: trusty
before_install:
  - npm i -g gulp
install:
  - npm install
deploy:
  provider: npm
  skip_cleanup: true
  email: pengchengou@gmail.com
  api_key: 
    secure: 4316f3c0-0efb-4dec-90b7-da71fa523ed5
  on:
    tags: true
    repo: vxhly/descartes-sku.js
